# Generated by Django 2.2.10 on 2020-08-09 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Postt',
        ),
        migrations.RenameField(
            model_name='postt',
            old_name='Post',
            new_name='Poste',
        ),
    ]
