# Generated by Django 2.2.10 on 2020-08-09 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20200809_0747'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postt',
            old_name='Poste',
            new_name='desc',
        ),
    ]
