# Generated by Django 2.2.10 on 2020-08-12 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20200809_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='postt',
            name='image',
            field=models.ImageField(default=-1.0, upload_to=''),
            preserve_default=False,
        ),
    ]
